name: Scrape provincial data from sacoronavirus.co.za and/or nicd.ac.za
# The NICD data is release typically between 18:00 and 20:00.  Run this every 5 mins between those times   
# Adjusted to GMT+0 times
# This runner takes some time to setup, if we need to install R first.  

# test this locally by using the "act" tool:  https://github.com/nektos/act
# need to download the "full" version of the image, as R is not installed in the medium image.
# docker pull catthehacker/ubuntu:full-20.04
# act -j dailystats_scrape
# check the ~/.actrc file for mappings between ubuntu-20.04 and the full or medium images....

on:
  schedule:
    - cron: '*/5 16-18 * * *'

jobs:
  dailystats_scrape:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
# No need for this very length step, as R 4.1.0 is already installed on the base image.
#      - name: Set up R
#        uses: r-lib/actions/setup-r@v1
#        with:
#          r-version: '3.5.3'   # we don't need the latest R;  older versions are smaller and quicker to install.
      - name: OS dependencies
        run: |
          # remove mongo - otherwise the config below fails
          sudo apt-get remove mongodb-org-server -y
          sudo apt-get update -qq && exit 0
          sudo apt-get install --no-install-recommends software-properties-common dirmngr
          sudo wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
          # add the R 4.0 repo from CRAN -- adjust 'focal' to 'groovy' or 'bionic' as needed
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/"          
          sudo apt-get install libcurl4-openssl-dev libmagick++-dev libpoppler-cpp-dev -y --fix-missing
          sudo apt-get install r-cran-httr r-cran-xml2 r-cran-xml r-cran-data.table r-cran-git2r r-cran-magick r-cran-magrittr  -y --fix-missing
      - name: Install dependencies
        run: |
          install.packages(c("git2r", "magrittr"), repos="https://cran.r-project.org/")
        shell: Rscript --vanilla {0}
      - name: Scrape data 
        run: Rscript --vanilla 'scripts/daily_prov_scraper.R'
      - name: Commit and push changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              git commit -m "Update Provincial Vaccinations Data" -a
              git push origin master
          fi
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

